format = """$env_var $all"""

[env_var.STARSHIP_DISTRO]
format   = '[$env_value](white)'
variable = 'STARSHIP_DISTRO'
disabled = false

[aws]
format            = 'on [$symbol($region)]($style) '
symbol            = 'îŒ½ '
expiration_symbol = ''

[battery]
full_symbol        = 'ï•¸ '
charging_symbol    = 'ï–ƒ '
discharging_symbol = 'ï–‚ '

[character]
error_symbol   = '[->](bold red)'
success_symbol = '[->](bold green)'
disabled       = true

[conda]
symbol = 'ï„Œ '

[dart]
symbol = 'î˜ '

[directory]
truncation_length = 1
home_symbol       = 'ïŸ ~'
read_only_style   = '197'
read_only         = ' ï€£'

[docker_context]
symbol = 'ïŒˆ '

[elixir]
symbol = 'î‰µ '

[elm]
symbol = 'î˜¬ '

[gcloud]
format = 'on [$symbol($region)]($style) '
symbol = 'îŒ½ '

[git_branch]
symbol = 'ï˜ '

[git_status]
format   = '([\[ $all_status$ahead_behind\]]($style) )'

# $all_status
stashed    = '[ï£–$count](bold white) '
modified   = '[ï„$count](bold yellow) '
staged     = '[+$count](bold green) '
renamed    = '[ïª¶$count](bold yellow) '
deleted    = '[ï€”$count](bold red) '
conflicted = "[ğŸ³](bold red) "
untracked  = "[ï”©](bold yellow) "

# $ahead_behind
diverged   = '[â‡¡$ahead_countâ‡£$behind_count](bold yellow) )'
ahead      = '[â‡¡$count](bold yellow) '
behind     = '[â‡£$count](bold red) '
up_to_date = "[ï†](bold green) "

[golang]
symbol = 'î˜§ '

[hg_branch]
symbol = 'ï˜ '

[java]
symbol = 'î‰– '

[julia]
symbol = 'î˜¤ '

[kubernetes]
symbol   = 'ï´± '
disabled = false

[memory_usage]
symbol = 'ï¡š '

[nim]
symbol = 'ïš¤ '

[nix_shell]
symbol = 'ï‹œ '

[nodejs]
symbol = 'î‰ '

[package]
symbol = 'ï£– '

[perl]
symbol = 'î© '

[php]
symbol = 'î˜ˆ '

[python]
python_binary = 'python3'
style         = 'green bold'
symbol        = 'î˜† '

[ruby]
symbol = 'îˆ¾ '

[rust]
symbol = 'î¨ '

[swift]
symbol = 'ï¯£ '
